source "https://rubygems.org"

# Use local edfize gem
gem "edfize", path: "/Users/adampallozzi/Code/gems/edfize"

# If you want to specify the version:
# gem "edfize", "0.6.0", path: "/Users/adampallozzi/Code/gems/edfize"
