AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  NewCops: enable

# Documentation is present at the module level
Style/Documentation:
  Enabled: false

# These metrics are too strict for this codebase
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Max: 40
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10

# Allow longer lines for readability
Layout/LineLength:
  Max: 160

# Class style preferences
Style/ClassAndModuleChildren:
  Enabled: false

# String literal preferences
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# Allow more flexible code style
Style/PerlBackrefs:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/FormatStringToken:
  Enabled: false

# Lambda style
Style/Lambda:
  EnforcedStyle: literal

# Naming conventions
Naming/HeredocDelimiterNaming:
  Enabled: false

# Bundler configuration
Bundler/GemFilename:
  Enabled: false

# Gemspec configuration
Gemspec/RequiredRubyVersion:
  Enabled: false